# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CGJi8hU-snid8ASMLz8p1plTlpAQHqdu
"""

import pandas as pd
import random as random
from google.colab import drive 
drive.mount('/content/Mydrive')

reader = pd.read_csv('/content/Mydrive/MyDrive/sample_submission.csv')
id = reader['id']
ndf =pd.DataFrame('id')
arr = []
for row in id :
  arr.apend(random.randint(0,1))